### ISSUE TITLE
Bug: delay undefined

### ISSUE THREAD

**Issue by alecthw** [jaywcjlove/mocker-api#289]
Node: v16.14.2
Mocker Api: 2.9.5

mock\index.js
``` js
const { delay } = require('mocker-api');
const noProxy = process.env.NO_PROXY === 'true';

const proxy = {
  'GET /api/user': {
    id: 1,
    username: 'kenny',
    sex: 6,
  },
};

module.exports = noProxy ? {} : delay(proxy, 1000);
```

run with cmd

``` bash
mocker mock
```

``` log
> mocker mock        

D:\WebstormProjects\my-parcel\mock\index.js:12
module.exports = noProxy ? {} : delay(proxy, 1000);
                                ^

TypeError: delay is not a function
    at Object.<anonymous> (D:\WebstormProjects\my-parcel\mock\index.js:12:33)   
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) 
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at D:\WebstormProjects\my-parcel\node_modules\mocker-api\lib\index.js:200:32
    at Array.reduce (<anonymous>)
    at getConfig (D:\WebstormProjects\my-parcel\node_modules\mocker-api\lib\index.js:199:27)
```

debug image
![image](https://user-images.githubusercontent.com/22856212/162192253-0edc2050-b2d1-4cf9-9847-4ebb15930e91.png)

**Comment by jaywcjlove** [comment]
@alecthw `const delay = require('mocker-api/lib/delay');`

你先使用这种方式解决一下，我看一下什么情况

**Comment by jaywcjlove** [comment]
```js
const delay = require('mocker-api/delay');
// or
const delay = require('mocker-api/lib/delay');
```
