### ISSUE TITLE
使用proxy时报错

### ISSUE THREAD

**Issue by Yukippe** [jaywcjlove/mocker-api#64]
浏览器报错如下：  
```
TypeError: Unexpected MODIFIER at 7, expected END
    at mustConsume (... \node_modules\mocker-api\node_modules\path-to-regexp\dist\index.js:113:15)
    at parse (... \node_modules\mocker-api\node_modules\path-to-regexp\dist\index.js:172:9)
    at stringToRegexp (D:\yukippe\memberCenter\node_modules\mocker-api\node_modules\path-to-regexp\dist\index.js:329:27)
    at pathToRegexp (... \node_modules\mocker-api\node_modules\path-to-regexp\dist\index.js:403:12)
    at  ... \node_modules\mocker-api\src\index.js:83:16
    at Array.find (<anonymous>)
    at ... \node_modules\mocker-api\src\index.js:82:45
    at Layer.handle [as handle_request] (... \node_modules\express\lib\router\layer.js:95:5)
    at next (... \node_modules\express\lib\router\route.js:137:13)
    at next (... \node_modules\express\lib\router\route.js:131:14)
```
--- 
使用方式如下 
系统：win10
webpack.config.js： 
```
  devServer: {
...
    before(app){
      apiMocker(app, path.resolve('./mock/mock.js'))
    },
  }, 
```
mock.js : 
```
const _proxy = process.env.proxy == 'true';
let proxy = {};
if(_proxy) {
  proxy={
    _proxy : {
      proxy : {
        "/api/*":"http://127.0.0.1:9090/"
      },
      changeHost: true
    }
  };
} else {
  proxy = {
    'GET /api/user': {id: 1, username: 'kenny', sex: 6 },
    'GET /api/user/list': [
      {id: 1, username: 'kenny', sex: 6 },
      {id: 2, username: 'kenny', sex: 6 }
    ],
    'POST /api/login/account': (req, res) => {
      const { password, username } = req.body;
      if (password === '888888' && username === 'admin') {
        return res.send({
          status: 'ok',
          code: 0,
          token: "sdfsdfsdfdsf",
          data: {id: 1, username: 'kenny', sex: 6 }
        });
      } else {
        return res.send({status: 'error', code: 403 });
      }
    },
    'DELETE /api/user/:id': (req, res) => {
      console.log('---->', req.body)
      console.log('---->', req.params.id)
      res.send({ status: 'ok', message: '删除成功！' });
    }
  }
}
module.exports = proxy
```
当使用proxy时候， 浏览器就会出现上述错误。
使用example/webpack 同样会出现path-to-regexp相关的错误

**Comment by jaywcjlove** [comment]
@Yukippe Node.js/npm 什么版本? 我本机 Mac/Linux 是没有这个错误的。

**Comment by Yukippe** [comment]
```
 proxy={
    _proxy : {
      proxy : {
        "/api/*":"http://127.0.0.1:9090/"
      },
      changeHost: true
    }
  };
```
通配符的问题。 改成`/api/(.*)`貌似就没问题了。 我已经关闭此issues了。
